# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

windowrule {
  name = windowrule-1
  workspace = 9
  match:class = ^([Ss]potify)$
}

windowrule {
  name = windowrule-2
  workspace = 8
  match:class = ^([Vv]esktop)$
}


bind = $ca, G, exec, steam
bind = $ca, S, exec, spotify
# bind = $ca, D, exec, discord
bind = $ca, D, exec, vesktop
bind = $mainMod SHIFT, G, exec, pkill -x rofi || $scrPath/gamelauncher.sh 4 # steam game launcher // install steam
bind = $ca, DELETE, exec, swaylock;systemctl suspend
bind = $ca, Y, exec, $BROWSER https://youtube.com
bind = ,XF86Calculator, exec, $term
bind = ,XF86Launch2, exec, $BROWSER
bind = ,XF86Launch2, exec, spotify
bind = ,XF86Launch2, exec, vesktop
# See https://wiki.hypr.land/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,gr
    numlock_by_default = false
    # kb_layout = us
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat
    # numlock_by_default = true

    # 🔗 See https://wiki.hypr.land/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = true
        scroll_factor = 0.4
    }
}
